### ISSUE TITLE
Errors in 2017 CA catches in PacFIN 

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [JaneSullivan-NOAA/shortspine_thornyhead_2023#16]
On March 10, 2023, Kiva Oken informed our thornyhead assessment team that 2017 CA catches in PacFIN have errors and need to be corrected. Because it will take a long time to fix PacFIN, CA staff are going to email Kiva catches for 2017 summarized by trawl and non-trawl. Kiva will share these aggregated catches with us, and we will need to hard code these catches in the landings R script.
@haleyoleynik @adamlhayes @pyhernvann @Ovec8hkin

**Comment by JaneSullivan-NOAA** [comment]
from @okenk:

> Here are those promised catches for 2017 in California. For this year only these should be used in lieu of PacFIN. You can ignore the line for petrale. CDFW also provided all available Calcom landings data with pivot tables sorting out the 2017 annual landings by the 2 main fleets. Here is where she sourced the data: https://calcom.psmfc.org/qry_all_landings.asp

Species | Non-Trawl (mt) | Trawl (mt)
-- | -- | --
Shortspine thornyhead | 184.77 | 158.30

**Comment by adamlhayes** [comment]
OK - this is done and pushed out for the fishery_landings R file. I also updated the OR catch for 1981-1986 with state data, and re-ran the figures. I didn't get the chance to look at SST_PacFIN_Fishery_Landings_2023.R and wasn't sure if that was a file that was still active anyway.
