### ISSUE TITLE
bug in fishery landed catch length comp second expansion?

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [JaneSullivan-NOAA/shortspine_thornyhead_2023#22]
The results of the second expansion look flattened, all the sexes look the same for south trawl. 
- potentially try doing the expansion for males, females, and unsexed fisheries separately, combine after.
- also step through the pacfin utilities code and post issue there if need be.
- will bring  this issue to the instructors on Thursday	
![image](https://user-images.githubusercontent.com/68303089/228662705-c09ce690-a3d8-4023-8bdd-8a53f68145b3.png)

**Comment by haleyoleynik** [comment]
Okay, I did some initial digging and it looks like the issue may not be with the expansions but is either happening in the PacFin Utilities function `getComps()` or in our data wrangling (after [line 280](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/blob/e40e76c316fcc7389356cadcf54c8853511103a8/R/landings/SST_PacFIN_expansion.R#L280) in the length comp code)
- Length distributions before this point (after the first and second expansions) [look okay](https://docs.google.com/presentation/d/1tJ0B4Ch14V3xKqTK0jz_4sOj8VQli1NA7fQ38SRBRHw/edit#slide=id.g21071301684_0_0) - although they look almost exactly the same to me after the first and after the second expansion. 
- I'll continue looking into this later, but wanted to leave a note about where I left it right now.

**Comment by haleyoleynik** [comment]
@Ovec8hkin, yes you're right - and I just did another comparison of raw data to post second expansion data and they look fine now - so it doesn't seem like it's the expansion that was causing that issue ([see slide 21 and 22](https://docs.google.com/presentation/d/1tJ0B4Ch14V3xKqTK0jz_4sOj8VQli1NA7fQ38SRBRHw/edit#slide=id.g228cfcdcfe6_0_7))

**Comment by Ovec8hkin** [comment]
@haleyoleynik It looks like getComps relies on there being a column "sex" or something similar in the data frame or else it assigns everything to unsexed. Is our data formatted correctly?
https://github.com/pfmc-assessments/PacFIN.Utilities/blob/689f7dbc6b299e696466290435f85ba861ac7563/R/getComps.R#L119
