### ISSUE TITLE
Max cutoff length for assigning unsexed fish to male or female

### ISSUE THREAD

**Issue by JaneSullivan-NOAA** [JaneSullivan-NOAA/shortspine_thornyhead_2023#8]
Many small fish are difficult to sex because their gonads have not fully developed. One way we can address this issue is by assuming a 50/50 sex ratio for unsexed fish below a certain size. I chose [<= 16 cm](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/blob/f509727bd6eecabbe2e69e911f32a8d2b7647974/R/survey/survey_data.R#L49) because it accounted for 75% of the unsexed fish in years when there were also sexed fish available.

This affects:
- length-weight results
- fishery and survey length comp data
- other? growth?

@Ovec8hkin

**Comment by Ovec8hkin** [comment]
Will start investigating this soon. 

Initial thoughts are that this strategy is generically fine. The other way that I can think of would be using a maturity-at-length curve and finding the size (length) at which some percentage (say 75%) of fish are mature and using that size rather than the data derived length.

@JaneSullivan-NOAA Do you know what the form of the maturity data we are getting is (I think Sabrina was working with this, but I can't find her GitHub handle)? Is it maturity at age? Maturity at length?

**Comment by JaneSullivan-NOAA** [comment]
It will be maturity-at-length data from the NWFSCcombo survey and port samples. Melissa Head says these data will be available in late Feb to mid March.

The current maturity info is from Pearson and Gunderson 2003. I added a [script](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/blob/main/R/bio/maturity.R) to produce this figure and [write a csv](https://github.com/JaneSullivan-NOAA/shortspine_thornyhead_2023/tree/main/outputs/maturity) of proportions maturity for our assessment length bins. The length at 75% maturity for this curve is 18.67, but we should note how steep this maturity curve is...
![pearson_maturity_length](https://user-images.githubusercontent.com/68303089/218530677-c0ea8078-0485-451a-bb4e-abaecd95cbde.png)

**Comment by Ovec8hkin** [comment]
Great. Thanks @JaneSullivan-NOAA. I will definitely have comments on this by team meeting on Friday, but let me know if you need thoughts back sooner than that.

**Comment by sabrinabeyer** [comment]
![image](https://user-images.githubusercontent.com/63366861/218558404-9aafd6fd-57af-4548-95ad-289a3afdb023.png)

This was the input in the control file for maturity in the 2013 assessment. Looks like they explored two options of specifying a logistic regression on length (Pearson and Gunderson 2003, correct?), and also exploring a percent mature by group (length bin?). Jane is correct that the new data will be by length (no new age information for this species). 

I agree that we should explore sensitivity to the slope of the maturity curve. Does the updated SS3 model allow us to add uncertainty to the parameters? I will check that out.

We will also have spatial (north/south) information associated with the maturity data and can see if there is enough data to explore differences in north/ south. 

For the bridge model...try the Pearson and Gunderson 2003 logistic curve (I believe that was in the final 2013 model).

**Comment by Ovec8hkin** [comment]
Just did some analysis (see `R/unsexed_length_analysis.R`) regarding this. 16cm seems completely reasonable for now. Once we have maturity-at-length data, I would recommend using that to see what proportion of the population would be mature at 16cm. If its 75% or more, then I dont see a problem using it. If theres still a large portion of the population that is immature ay 16cm, then maybe we move that boundary to a larger length.

For now, 16cm is fine.

**Comment by JaneSullivan-NOAA** [comment]
Looks great, thanks. It's good to remember that the Pearson and Gunderson study was on female-only fish and was only one year of data. There is also very little difference between the male and female L-W relationships (see the figure in the ppt). My vote is to stick with 16 cm.

**Comment by Ovec8hkin** [comment]
Didn't realize that the Pearson and Gunderson study was such low sample size. Given that, 16cm is more than fine for now. If we get a good sample size and data from both sexes for 2023, I still think setting the cutoff based on a maturity-at-length proportion would be a good idea. But we can discuss that later, once we have the maturity data.
